# Documentation for ACL policy: https://aka.ms/gim/docs/policy/acl
name: Access control list
description: List of teams and their permission levels
resource: repository
where:
configuration:
  manageAccess:
    - member: jpalma_microsoft
      role: Maintain
    - member: shasb_microsoft
      role: Maintain
    - member: jpang_microsoft
      role: Maintain
    - member: qike_microsoft
      role: Maintain
    - member: matthchr_microsoft
      role: Maintain
    # Azure Container Service - Approver
    - team: rrd-acsappr-25810
      role: Maintain
    - team: RCG-ACSAPPR-26695
      role: Maintain
    # Sean McKenna's Organization FTE
    - team: SeanMcKOrgFTE
      role: Write
    # Qi Ke's Organization FTE
    - team: QiKeOrgFTE
      role: Write
    # API Approvers
    - team: aks-api-reviewers-eng
      role: Write
    - team: aks-api-reviewers-pms
      role: Write
    # PRD approvers
    - team: aks-prd-reviewers
      role: Write
    # Design approvers
    - team: aks-design-reviewers
      role: Write
    # Azure Container Service - AKS-RO
    - team: azurecontainerservice-aks-ro-eb62
      role: Read
    - team: RAM_ae99a8e2-4235-4ab1-b88c-fa7cc1419bb0
      role: Read
    - team: RAM_3c9edc39-6b05-46b7-bf9f-ff48b5e0e870
      role: Read
    # Networking (Chandan's team, as well as Neha's + Miguel's)
    - team: caggart
      role: Read
    - team: miguelgo_team
      role: Read
    - team: neaggarwt
      role: Read
    # Portal
    - team: pcnx-pm
      role: Read
    - team: pcnx-devleads
      role: Read
