# Documentation for ACL policy: https://aka.ms/gim/docs/policy/acl

name: Access control list
description: List of teams and their permission levels
resource: repository
where:
configuration:
  manageAccess:
  - member: jpang
    role: Maintain
  - team: qi-lt
    role: Maintain
  - member: qike
    role: Maintain
  # Azure Container Service - CG-Read Write
  - team: "rrd-read write-rg-22938"
    role: Write
  # Azure Container Service - NTDEV CG-Read Write
  - team: "azurecontainerservice-rg-readwritentdev-8295"
    role: Write